/* ============================================================
   data.js  –  Shainy Creation Admin Panel
   Shared mock data used by all page scripts.
   ============================================================ */

/* ── ORDERS ─────────────────────────────────────────────── */
const SC_ORDERS = [
  {
    id: "SC-1051",
    customer: "Priya Mehta",
    phone: "+91 98201 11111",
    address: "12 Rose Lane, Koramangala, Bengaluru 560034",
    product: "Rosabay Belle Frock",
    sku: "SC-RBF-001",
    qty: 2,
    amount: 4800,
    payment: "Razorpay",
    date: "2024-01-15",
    status: "Pending",
    dress: "dress-pink",
  },
  {
    id: "SC-1050",
    customer: "Ananya Shah",
    phone: "+91 98202 22222",
    address: "7 Jasmine Ave, Bandra West, Mumbai 400050",
    product: "Golden Gown Deluxe",
    sku: "SC-GGD-002",
    qty: 1,
    amount: 3200,
    payment: "UPI",
    date: "2024-01-15",
    status: "Processing",
    dress: "dress-gold",
  },
  {
    id: "SC-1049",
    customer: "Kavya Nair",
    phone: "+91 98203 33333",
    address: "3 Tulip St, T Nagar, Chennai 600017",
    product: "Tutu Princess Set",
    sku: "SC-TPS-003",
    qty: 3,
    amount: 2100,
    payment: "COD",
    date: "2024-01-14",
    status: "Shipped",
    dress: "dress-lavender",
  },
  {
    id: "SC-1048",
    customer: "Riya Sharma",
    phone: "+91 98204 44444",
    address: "45 Lotus Rd, Sector 15, Noida 201301",
    product: "Ivory Dream Frock",
    sku: "SC-IDF-004",
    qty: 1,
    amount: 1890,
    payment: "Razorpay",
    date: "2024-01-14",
    status: "Delivered",
    dress: "dress-white-ph",
  },
  {
    id: "SC-1047",
    customer: "Sneha Iyer",
    phone: "+91 98205 55555",
    address: "8 Orchid Blvd, Koregaon Park, Pune 411001",
    product: "Coral Blossom Gown",
    sku: "SC-CBG-005",
    qty: 2,
    amount: 5600,
    payment: "Paytm",
    date: "2024-01-13",
    status: "Delivered",
    dress: "dress-coral",
  },
  {
    id: "SC-1046",
    customer: "Meera Pillai",
    phone: "+91 98206 66666",
    address: "22 Marigold St, Indiranagar, Bengaluru 560038",
    product: "Sky Blue Tutu",
    sku: "SC-SBT-006",
    qty: 1,
    amount: 1400,
    payment: "UPI",
    date: "2024-01-13",
    status: "Returned",
    dress: "dress-blue",
  },
  {
    id: "SC-1045",
    customer: "Diya Kapoor",
    phone: "+91 98207 77777",
    address: "14 Sunflower Rd, Adyar, Chennai 600020",
    product: "Mint Fresh Frock",
    sku: "SC-MFF-007",
    qty: 2,
    amount: 3360,
    payment: "Razorpay",
    date: "2024-01-12",
    status: "Delivered",
    dress: "dress-mint",
  },
  {
    id: "SC-1044",
    customer: "Aanya Verma",
    phone: "+91 98208 88888",
    address: "31 Peony Ln, Salt Lake, Kolkata 700064",
    product: "Sunshine Yellow Gown",
    sku: "SC-SYG-008",
    qty: 1,
    amount: 2240,
    payment: "COD",
    date: "2024-01-12",
    status: "Processing",
    dress: "dress-yellow",
  },
  {
    id: "SC-1043",
    customer: "Siya Reddy",
    phone: "+91 98209 99999",
    address: "6 Dahlia Close, Jubilee Hills, Hyderabad 500033",
    product: "Rosabay Belle Frock",
    sku: "SC-RBF-001",
    qty: 1,
    amount: 2400,
    payment: "UPI",
    date: "2024-01-11",
    status: "Shipped",
    dress: "dress-pink",
  },
  {
    id: "SC-1042",
    customer: "Tara Menon",
    phone: "+91 98210 10101",
    address: "9 Hibiscus Way, MG Road, Bengaluru 560001",
    product: "Golden Gown Deluxe",
    sku: "SC-GGD-002",
    qty: 2,
    amount: 6400,
    payment: "Razorpay",
    date: "2024-01-11",
    status: "Delivered",
    dress: "dress-gold",
  },
  {
    id: "SC-1041",
    customer: "Nisha Gupta",
    phone: "+91 98211 11211",
    address: "18 Lavender Lane, Powai, Mumbai 400076",
    product: "Red Rose Gown",
    sku: "SC-RRG-009",
    qty: 1,
    amount: 2800,
    payment: "Paytm",
    date: "2024-01-10",
    status: "Pending",
    dress: "dress-red",
  },
  {
    id: "SC-1040",
    customer: "Pooja Joshi",
    phone: "+91 98212 12312",
    address: "5 Carnation St, Civil Lines, Delhi 110054",
    product: "Tutu Princess Set",
    sku: "SC-TPS-003",
    qty: 2,
    amount: 2800,
    payment: "COD",
    date: "2024-01-10",
    status: "Delivered",
    dress: "dress-lavender",
  },
  {
    id: "SC-1039",
    customer: "Isha Patel",
    phone: "+91 98213 13413",
    address: "27 Chrysanthemum Rd, Navrangpura, Ahmedabad 380009",
    product: "Ivory Dream Frock",
    sku: "SC-IDF-004",
    qty: 3,
    amount: 5670,
    payment: "UPI",
    date: "2024-01-09",
    status: "Processing",
    dress: "dress-white-ph",
  },
  {
    id: "SC-1038",
    customer: "Mia D'Souza",
    phone: "+91 98214 14514",
    address: "11 Azalea Ave, Panaji, Goa 403001",
    product: "Coral Blossom Gown",
    sku: "SC-CBG-005",
    qty: 1,
    amount: 2800,
    payment: "Razorpay",
    date: "2024-01-09",
    status: "Shipped",
    dress: "dress-coral",
  },
  {
    id: "SC-1037",
    customer: "Zara Khan",
    phone: "+91 98215 15615",
    address: "3 Poppy Rd, Hazratganj, Lucknow 226001",
    product: "Sky Blue Tutu",
    sku: "SC-SBT-006",
    qty: 2,
    amount: 2800,
    payment: "COD",
    date: "2024-01-08",
    status: "Returned",
    dress: "dress-blue",
  },
];

/* ── PRODUCTS ────────────────────────────────────────────── */
const SC_PRODUCTS = [
  {
    id: "p1",
    name: "Rosabay Belle Frock",
    sku: "SC-RBF-001",
    price: 2400,
    compare: 3000,
    category: "Frocks",
    age: "3–6 Yrs",
    stock: 42,
    status: "Active",
    featured: true,
    sales: 128,
    dress: "dress-pink",
  },
  {
    id: "p2",
    name: "Golden Gown Deluxe",
    sku: "SC-GGD-002",
    price: 3200,
    compare: 4000,
    category: "Gowns",
    age: "6–10 Yrs",
    stock: 18,
    status: "Active",
    featured: true,
    sales: 97,
    dress: "dress-gold",
  },
  {
    id: "p3",
    name: "Tutu Princess Set",
    sku: "SC-TPS-003",
    price: 1400,
    compare: 1800,
    category: "Tutus",
    age: "1–3 Yrs",
    stock: 65,
    status: "Active",
    featured: false,
    sales: 214,
    dress: "dress-lavender",
  },
  {
    id: "p4",
    name: "Ivory Dream Frock",
    sku: "SC-IDF-004",
    price: 1890,
    compare: 2400,
    category: "Frocks",
    age: "3–6 Yrs",
    stock: 30,
    status: "Active",
    featured: false,
    sales: 76,
    dress: "dress-white-ph",
  },
  {
    id: "p5",
    name: "Coral Blossom Gown",
    sku: "SC-CBG-005",
    price: 2800,
    compare: 3500,
    category: "Gowns",
    age: "6–10 Yrs",
    stock: 12,
    status: "Active",
    featured: true,
    sales: 55,
    dress: "dress-coral",
  },
  {
    id: "p6",
    name: "Sky Blue Tutu",
    sku: "SC-SBT-006",
    price: 1400,
    compare: 1800,
    category: "Tutus",
    age: "0–1 Yrs",
    stock: 80,
    status: "Active",
    featured: false,
    sales: 189,
    dress: "dress-blue",
  },
  {
    id: "p7",
    name: "Mint Fresh Frock",
    sku: "SC-MFF-007",
    price: 1680,
    compare: 2100,
    category: "Frocks",
    age: "3–6 Yrs",
    stock: 28,
    status: "Active",
    featured: false,
    sales: 63,
    dress: "dress-mint",
  },
  {
    id: "p8",
    name: "Sunshine Yellow Gown",
    sku: "SC-SYG-008",
    price: 2240,
    compare: 2800,
    category: "Gowns",
    age: "6–10 Yrs",
    stock: 9,
    status: "On Hold",
    featured: false,
    sales: 41,
    dress: "dress-yellow",
  },
  {
    id: "p9",
    name: "Red Rose Gown",
    sku: "SC-RRG-009",
    price: 2800,
    compare: 3400,
    category: "Gowns",
    age: "10–14 Yrs",
    stock: 22,
    status: "Active",
    featured: true,
    sales: 88,
    dress: "dress-red",
  },
  {
    id: "p10",
    name: "Lavender Cloud Tutu",
    sku: "SC-LCT-010",
    price: 1200,
    compare: 1500,
    category: "Tutus",
    age: "1–3 Yrs",
    stock: 54,
    status: "Active",
    featured: false,
    sales: 102,
    dress: "dress-lavender",
  },
  {
    id: "p11",
    name: "Blush Princess Frock",
    sku: "SC-BPF-011",
    price: 2100,
    compare: 2600,
    category: "Frocks",
    age: "3–6 Yrs",
    stock: 0,
    status: "Active",
    featured: false,
    sales: 49,
    dress: "dress-pink",
  },
  {
    id: "p12",
    name: "Festive Gold Set",
    sku: "SC-FGS-012",
    price: 3600,
    compare: 4500,
    category: "Sets",
    age: "6–10 Yrs",
    stock: 15,
    status: "Draft",
    featured: false,
    sales: 0,
    dress: "dress-gold",
  },
];

/* ── BULK ORDERS ─────────────────────────────────────────── */
const SC_BULK_ORDERS = [
  {
    id: "BO-0048",
    company: "Little Angels Academy",
    contact: "Rekha Subramaniam",
    phone: "+91 94400 11111",
    address: "120 School Rd, Bengaluru 560076",
    products: ["Rosabay Belle Frock", "Sky Blue Tutu"],
    qty: 120,
    value: 192000,
    date: "2024-01-15",
    status: "Pending Approval",
  },
  {
    id: "BO-0047",
    company: "Rainbow Kids Store",
    contact: "Deepa Nair",
    phone: "+91 94401 22222",
    address: "45 Market St, Kochi 682016",
    products: ["Tutu Princess Set", "Mint Fresh Frock"],
    qty: 80,
    value: 116800,
    date: "2024-01-14",
    status: "Approved",
  },
  {
    id: "BO-0046",
    company: "Sparkle Boutique Pvt Ltd",
    contact: "Shreya Mehta",
    phone: "+91 94402 33333",
    address: "8 Fashion Ave, Mumbai 400001",
    products: ["Golden Gown Deluxe"],
    qty: 50,
    value: 160000,
    date: "2024-01-12",
    status: "Processing",
  },
  {
    id: "BO-0045",
    company: "Princess Wardrobe",
    contact: "Kavitha Raj",
    phone: "+91 94403 44444",
    address: "22 Park Rd, Chennai 600002",
    products: ["Coral Blossom Gown", "Red Rose Gown"],
    qty: 40,
    value: 112000,
    date: "2024-01-10",
    status: "Shipped",
  },
  {
    id: "BO-0044",
    company: "Kiddo Fashion Hub",
    contact: "Anita Sharma",
    phone: "+91 94404 55555",
    address: "5 Commerce Nagar, Delhi 110092",
    products: ["Rosabay Belle Frock"],
    qty: 60,
    value: 144000,
    date: "2024-01-08",
    status: "Delivered",
  },
  {
    id: "BO-0043",
    company: "Fairy Tale Kids",
    contact: "Preethi Rao",
    phone: "+91 94405 66666",
    address: "17 Mall Rd, Pune 411001",
    products: ["Ivory Dream Frock", "Sky Blue Tutu"],
    qty: 35,
    value: 66150,
    date: "2024-01-05",
    status: "Cancelled",
  },
];

/* ── FRANCHISE REQUESTS ──────────────────────────────────── */
const SC_FRANCHISE = [
  {
    id: "FR-0012",
    name: "Sunita Bose",
    email: "sunita.bose@gmail.com",
    phone: "+91 93300 11111",
    city: "Kolkata",
    state: "West Bengal",
    investBudget: "₹10–15 Lakhs",
    experience: "5 yrs retail",
    message:
      "Interested in opening a franchise in South Kolkata. Have prior garment retail experience.",
    date: "2024-01-15",
    status: "New",
  },
  {
    id: "FR-0011",
    name: "Harish Menon",
    email: "harish.m@email.com",
    phone: "+91 93301 22222",
    city: "Kochi",
    state: "Kerala",
    investBudget: "₹8–12 Lakhs",
    experience: "2 yrs online",
    message: "Want to expand to Kochi. Currently running an online boutique.",
    date: "2024-01-13",
    status: "Under Review",
  },
  {
    id: "FR-0010",
    name: "Vandana Singh",
    email: "vandana.s@yahoo.com",
    phone: "+91 93302 33333",
    city: "Jaipur",
    state: "Rajasthan",
    investBudget: "₹15–20 Lakhs",
    experience: "8 yrs retail",
    message:
      "Seeking franchise in Vaishali Nagar. Strong customer base in kids fashion.",
    date: "2024-01-11",
    status: "Approved",
  },
  {
    id: "FR-0009",
    name: "Kiran Rao",
    email: "kiran.rao@hotmail.com",
    phone: "+91 93303 44444",
    city: "Hyderabad",
    state: "Telangana",
    investBudget: "₹12–18 Lakhs",
    experience: "3 yrs fashion",
    message: "Looking to open in Banjara Hills. Background in fashion retail.",
    date: "2024-01-09",
    status: "New",
  },
  {
    id: "FR-0008",
    name: "Lalitha Kumar",
    email: "lalitha.k@gmail.com",
    phone: "+91 93304 55555",
    city: "Coimbatore",
    state: "Tamil Nadu",
    investBudget: "₹6–10 Lakhs",
    experience: "No experience",
    message:
      "First-time business owner, very motivated. Willing to attend all training.",
    date: "2024-01-07",
    status: "Rejected",
  },
  {
    id: "FR-0007",
    name: "Preeti Agarwal",
    email: "preeti.a@email.com",
    phone: "+91 93305 66666",
    city: "Nagpur",
    state: "Maharashtra",
    investBudget: "₹10–15 Lakhs",
    experience: "4 yrs retail",
    message:
      "Nagpur market is ready for Shainy Creation. I have the perfect location.",
    date: "2024-01-04",
    status: "Under Review",
  },
];

/* ── CONTACT MESSAGES ────────────────────────────────────── */
const SC_CONTACTS = [
  {
    id: "CT-0085",
    name: "Priya Mehta",
    email: "priya.m@gmail.com",
    phone: "+91 99000 11111",
    subject: "Order Issue",
    message:
      "My order SC-1048 was delivered but the size is wrong. I ordered size 4-5 years but received 2-3 years. Please help.",
    date: "2024-01-15 10:24",
    status: "Unread",
  },
  {
    id: "CT-0084",
    name: "Rekha Das",
    email: "rekha.d@yahoo.com",
    phone: "+91 99001 22222",
    subject: "Product Query",
    message:
      "Do you have the Rosabay Belle Frock in dark pink color? The website only shows light pink. Also what is the fabric composition?",
    date: "2024-01-15 09:12",
    status: "Unread",
  },
  {
    id: "CT-0083",
    name: "Anjali Verma",
    email: "anjali.v@email.com",
    phone: "+91 99002 33333",
    subject: "Return Request",
    message:
      "I want to return order SC-1046. Product quality did not match the images online. Please initiate a refund.",
    date: "2024-01-14 16:48",
    status: "Read",
  },
  {
    id: "CT-0082",
    name: "Sundar Raj",
    email: "sundar.r@gmail.com",
    phone: "+91 99003 44444",
    subject: "General Enquiry",
    message:
      "Are you planning to open a store in Chennai? I love your products but online shopping is not convenient for me.",
    date: "2024-01-14 14:30",
    status: "Replied",
  },
  {
    id: "CT-0081",
    name: "Meena Pillai",
    email: "meena.p@hotmail.com",
    phone: "+91 99004 55555",
    subject: "Feedback",
    message:
      "The Golden Gown Deluxe was absolutely stunning! My daughter wore it to her cousin's wedding and everyone loved it. Thank you so much!",
    date: "2024-01-13 11:05",
    status: "Replied",
  },
  {
    id: "CT-0080",
    name: "Farida Khan",
    email: "farida.k@email.com",
    phone: "+91 99005 66666",
    subject: "Order Issue",
    message:
      "Order SC-1042 tracking shows delivered but I have not received the package. Please investigate.",
    date: "2024-01-12 18:22",
    status: "Read",
  },
  {
    id: "CT-0079",
    name: "Geetha Nair",
    email: "geetha.n@gmail.com",
    phone: "+91 99006 77777",
    subject: "Product Query",
    message:
      "What is the age range for the Tutu Princess Set? The website says 1-3 years but seems bigger in the photos.",
    date: "2024-01-11 09:45",
    status: "Archived",
  },
];

/* ── DISCOUNTS ───────────────────────────────────────────── */
const SC_DISCOUNTS = [
  {
    code: "PRINCESS20",
    type: "Percentage (%)",
    value: 20,
    min: 1000,
    limit: 500,
    uses: 284,
    start: "2024-01-01",
    end: "2024-03-31",
    applies: "All Products",
    active: true,
  },
  {
    code: "NEWBORN15",
    type: "Percentage (%)",
    value: 15,
    min: 500,
    limit: 200,
    uses: 87,
    start: "2024-01-10",
    end: "2024-02-28",
    applies: "Tutus Only",
    active: true,
  },
  {
    code: "GOLD500",
    type: "Fixed Amount (₹)",
    value: 500,
    min: 3000,
    limit: 100,
    uses: 42,
    start: "2024-01-05",
    end: "2024-01-31",
    applies: "Gowns Only",
    active: true,
  },
  {
    code: "FREESHIP",
    type: "Free Shipping",
    value: 0,
    min: 800,
    limit: null,
    uses: 512,
    start: "2023-12-01",
    end: "2024-12-31",
    applies: "All Products",
    active: true,
  },
  {
    code: "FIRSTORDER",
    type: "Percentage (%)",
    value: 10,
    min: 0,
    limit: null,
    uses: 128,
    start: "2023-11-01",
    end: "2024-12-31",
    applies: "First Order Only",
    active: true,
  },
  {
    code: "FESTIVE25",
    type: "Percentage (%)",
    value: 25,
    min: 2000,
    limit: 300,
    uses: 300,
    start: "2023-10-01",
    end: "2023-11-15",
    applies: "All Products",
    active: false,
  },
  {
    code: "SUMMER10",
    type: "Percentage (%)",
    value: 10,
    min: 500,
    limit: 500,
    uses: 490,
    start: "2023-05-01",
    end: "2023-07-31",
    applies: "Frocks Only",
    active: false,
  },
];

/* ── STORE LOCATIONS ─────────────────────────────────────── */
const SC_LOCATIONS = [
  {
    id: "loc1",
    name: "Bengaluru Main",
    manager: "Preethi Reddy",
    address: "123 Princess Lane, Koramangala",
    city: "Bengaluru",
    state: "Karnataka",
    pin: "560034",
    phone: "+91 80 4567 8900",
    email: "blr-main@shainycreation.com",
    hours: "Mon–Sat: 10 AM – 8 PM",
    revenue: 62400,
    orders: 48,
    staff: 12,
    status: "Active",
    lastActive: "2024-01-15",
  },
  {
    id: "loc2",
    name: "Mumbai Bandra",
    manager: "Shruti Kapoor",
    address: "45 Linking Road, Bandra West",
    city: "Mumbai",
    state: "Maharashtra",
    pin: "400050",
    phone: "+91 22 4567 8901",
    email: "mum-bandra@shainycreation.com",
    hours: "Mon–Sun: 11 AM – 9 PM",
    revenue: 54800,
    orders: 41,
    staff: 10,
    status: "Active",
    lastActive: "2024-01-15",
  },
  {
    id: "loc3",
    name: "Chennai T Nagar",
    manager: "Kavitha Suresh",
    address: "8 Usman Road, T Nagar",
    city: "Chennai",
    state: "Tamil Nadu",
    pin: "600017",
    phone: "+91 44 4567 8902",
    email: "chn-tnagar@shainycreation.com",
    hours: "Mon–Sat: 10 AM – 8 PM",
    revenue: 41200,
    orders: 32,
    staff: 8,
    status: "Active",
    lastActive: "2024-01-14",
  },
  {
    id: "loc4",
    name: "Hyderabad Jubilee",
    manager: "Rohini Rao",
    address: "22 Road No. 36, Jubilee Hills",
    city: "Hyderabad",
    state: "Telangana",
    pin: "500033",
    phone: "+91 40 4567 8903",
    email: "hyd-jubilee@shainycreation.com",
    hours: "Mon–Sat: 10 AM – 8 PM",
    revenue: 38600,
    orders: 29,
    staff: 7,
    status: "Active",
    lastActive: "2024-01-13",
  },
  {
    id: "loc5",
    name: "Pune Koregaon Park",
    manager: "",
    address: "4 North Main Road, Koregaon Park",
    city: "Pune",
    state: "Maharashtra",
    pin: "411001",
    phone: "",
    email: "pune@shainycreation.com",
    hours: "TBD",
    revenue: 0,
    orders: 0,
    staff: 0,
    status: "Coming Soon",
    lastActive: "–",
  },
];

/* ── REPORTS ─────────────────────────────────────────────── */
const SC_REPORTS = [
  {
    id: "RP-0031",
    customer: "Priya Mehta",
    email: "priya.m@gmail.com",
    order: "SC-1048",
    type: "Wrong Item Received",
    priority: "High",
    date: "2024-01-15",
    status: "Open",
    notes: "",
  },
  {
    id: "RP-0030",
    customer: "Meera Pillai",
    email: "meera.p@gmail.com",
    order: "SC-1046",
    type: "Damaged Product",
    priority: "High",
    date: "2024-01-14",
    status: "In Progress",
    notes: "Replacement dispatched via Blue Dart.",
  },
  {
    id: "RP-0029",
    customer: "Farida Khan",
    email: "farida.k@gmail.com",
    order: "SC-1042",
    type: "Delivery Problem",
    priority: "Medium",
    date: "2024-01-12",
    status: "In Progress",
    notes: "Raised query with courier partner.",
  },
  {
    id: "RP-0028",
    customer: "Anjali Verma",
    email: "anjali.v@gmail.com",
    order: "SC-1046",
    type: "Wrong Item Received",
    priority: "Medium",
    date: "2024-01-11",
    status: "Resolved",
    notes: "Full refund issued.",
  },
  {
    id: "RP-0027",
    customer: "Sundar Raj",
    email: "sundar.r@gmail.com",
    order: "SC-1039",
    type: "Payment Issue",
    priority: "High",
    date: "2024-01-10",
    status: "Open",
    notes: "",
  },
  {
    id: "RP-0026",
    customer: "Nisha Gupta",
    email: "nisha.g@gmail.com",
    order: "SC-1037",
    type: "Missing Item",
    priority: "Low",
    date: "2024-01-09",
    status: "Resolved",
    notes: "Missing item shipped separately.",
  },
  {
    id: "RP-0025",
    customer: "Diya Kapoor",
    email: "diya.k@gmail.com",
    order: "SC-1035",
    type: "Other",
    priority: "Low",
    date: "2024-01-07",
    status: "Closed",
    notes: "Query resolved over phone.",
  },
];

/* ── MEDIA / CONTENT ─────────────────────────────────────── */
const SC_MEDIA = [
  {
    id: "m1",
    name: "rosabay-belle-frock-front.jpg",
    type: "image",
    size: "1.2 MB",
    date: "2024-01-10",
    usedIn: "Rosabay Belle Frock",
    url: "",
  },
  {
    id: "m2",
    name: "golden-gown-hero.jpg",
    type: "image",
    size: "980 KB",
    date: "2024-01-10",
    usedIn: "Golden Gown Deluxe",
    url: "",
  },
  {
    id: "m3",
    name: "tutu-princess-set-1.jpg",
    type: "image",
    size: "1.1 MB",
    date: "2024-01-09",
    usedIn: "Tutu Princess Set",
    url: "",
  },
  {
    id: "m4",
    name: "tutu-princess-set-2.jpg",
    type: "image",
    size: "870 KB",
    date: "2024-01-09",
    usedIn: "Tutu Princess Set",
    url: "",
  },
  {
    id: "m5",
    name: "ivory-dream-front.jpg",
    type: "image",
    size: "1.4 MB",
    date: "2024-01-08",
    usedIn: "Ivory Dream Frock",
    url: "",
  },
  {
    id: "m6",
    name: "coral-blossom-hero.jpg",
    type: "image",
    size: "1.0 MB",
    date: "2024-01-08",
    usedIn: "Coral Blossom Gown",
    url: "",
  },
  {
    id: "m7",
    name: "sky-blue-tutu-main.jpg",
    type: "image",
    size: "750 KB",
    date: "2024-01-07",
    usedIn: "Sky Blue Tutu",
    url: "",
  },
  {
    id: "m8",
    name: "brand-banner-jan2024.jpg",
    type: "image",
    size: "2.1 MB",
    date: "2024-01-06",
    usedIn: "–",
    url: "",
  },
  {
    id: "m9",
    name: "mint-fresh-frock.jpg",
    type: "image",
    size: "890 KB",
    date: "2024-01-05",
    usedIn: "Mint Fresh Frock",
    url: "",
  },
  {
    id: "m10",
    name: "lookbook-video-jan.mp4",
    type: "video",
    size: "82 MB",
    date: "2024-01-04",
    usedIn: "–",
    url: "",
  },
  {
    id: "m11",
    name: "product-demo-gown.mp4",
    type: "video",
    size: "64 MB",
    date: "2024-01-03",
    usedIn: "Golden Gown Deluxe",
    url: "",
  },
  {
    id: "m12",
    name: "size-chart.pdf",
    type: "other",
    size: "340 KB",
    date: "2024-01-02",
    usedIn: "–",
    url: "",
  },
  {
    id: "m13",
    name: "care-instructions.pdf",
    type: "other",
    size: "180 KB",
    date: "2024-01-01",
    usedIn: "–",
    url: "",
  },
  {
    id: "m14",
    name: "sunshine-yellow-gown.jpg",
    type: "image",
    size: "1.1 MB",
    date: "2023-12-28",
    usedIn: "Sunshine Yellow Gown",
    url: "",
  },
  {
    id: "m15",
    name: "red-rose-gown-hero.jpg",
    type: "image",
    size: "1.3 MB",
    date: "2023-12-26",
    usedIn: "Red Rose Gown",
    url: "",
  },
  {
    id: "m16",
    name: "lavender-cloud-tutu.jpg",
    type: "image",
    size: "820 KB",
    date: "2023-12-24",
    usedIn: "Lavender Cloud Tutu",
    url: "",
  },
  {
    id: "m17",
    name: "blush-princess-frock.jpg",
    type: "image",
    size: "960 KB",
    date: "2023-12-22",
    usedIn: "Blush Princess Frock",
    url: "",
  },
  {
    id: "m18",
    name: "homepage-hero-banner.jpg",
    type: "image",
    size: "3.2 MB",
    date: "2023-12-20",
    usedIn: "–",
    url: "",
  },
  {
    id: "m19",
    name: "collection-teaser.mp4",
    type: "video",
    size: "110 MB",
    date: "2023-12-18",
    usedIn: "–",
    url: "",
  },
  {
    id: "m20",
    name: "brand-guidelines.pdf",
    type: "other",
    size: "2.4 MB",
    date: "2023-12-15",
    usedIn: "–",
    url: "",
  },
];

/* ── TRANSACTIONS (Finance) ──────────────────────────────── */
const SC_TRANSACTIONS = [
  {
    id: "TXN-9901",
    order: "SC-1051",
    customer: "Priya Mehta",
    gateway: "Razorpay",
    amount: 4800,
    date: "2024-01-15",
    status: "Pending",
  },
  {
    id: "TXN-9900",
    order: "SC-1050",
    customer: "Ananya Shah",
    gateway: "UPI",
    amount: 3200,
    date: "2024-01-15",
    status: "Success",
  },
  {
    id: "TXN-9899",
    order: "SC-1049",
    customer: "Kavya Nair",
    gateway: "COD",
    amount: 2100,
    date: "2024-01-14",
    status: "Pending",
  },
  {
    id: "TXN-9898",
    order: "SC-1048",
    customer: "Riya Sharma",
    gateway: "Razorpay",
    amount: 1890,
    date: "2024-01-14",
    status: "Success",
  },
  {
    id: "TXN-9897",
    order: "SC-1047",
    customer: "Sneha Iyer",
    gateway: "Paytm",
    amount: 5600,
    date: "2024-01-13",
    status: "Success",
  },
  {
    id: "TXN-9896",
    order: "SC-1046",
    customer: "Meera Pillai",
    gateway: "UPI",
    amount: 1400,
    date: "2024-01-13",
    status: "Refunded",
  },
  {
    id: "TXN-9895",
    order: "SC-1045",
    customer: "Diya Kapoor",
    gateway: "Razorpay",
    amount: 3360,
    date: "2024-01-12",
    status: "Success",
  },
  {
    id: "TXN-9894",
    order: "SC-1044",
    customer: "Aanya Verma",
    gateway: "COD",
    amount: 2240,
    date: "2024-01-12",
    status: "Pending",
  },
  {
    id: "TXN-9893",
    order: "SC-1043",
    customer: "Siya Reddy",
    gateway: "UPI",
    amount: 2400,
    date: "2024-01-11",
    status: "Success",
  },
  {
    id: "TXN-9892",
    order: "SC-1042",
    customer: "Tara Menon",
    gateway: "Razorpay",
    amount: 6400,
    date: "2024-01-11",
    status: "Success",
  },
];

/* ── BANK ACCOUNTS ───────────────────────────────────────── */
let SC_BANKS = [
  {
    id: "bank1",
    holder: "Shainy Mathew",
    bank: "HDFC Bank",
    last4: "4821",
    ifsc: "HDFC0001234",
    type: "Current",
    primary: true,
  },
  {
    id: "bank2",
    holder: "Shainy Mathew",
    bank: "SBI",
    last4: "9204",
    ifsc: "SBIN0005678",
    type: "Savings",
    primary: false,
  },
];

/* ── ACTIVITY FEED ───────────────────────────────────────── */
const SC_ACTIVITY = [
  {
    text: "New order <strong>SC-1051</strong> from Priya Mehta",
    time: "2 min ago",
  },
  {
    text: "Product <strong>Rosabay Belle Frock</strong> stock low (42 left)",
    time: "18 min ago",
  },
  {
    text: "Bulk order <strong>BO-0048</strong> awaiting approval",
    time: "1 hr ago",
  },
  {
    text: "Franchise request from <strong>Sunita Bose</strong> (Kolkata)",
    time: "2 hrs ago",
  },
  {
    text: "New message from <strong>Rekha Das</strong> – Product Query",
    time: "3 hrs ago",
  },
  {
    text: "Order <strong>SC-1047</strong> marked as Delivered",
    time: "5 hrs ago",
  },
  {
    text: "Discount code <strong>PRINCESS20</strong> used 284 times",
    time: "6 hrs ago",
  },
];

/* ── HELPER FUNCTIONS ────────────────────────────────────── */
function fmtCurrency(n) {
  return "₹" + Number(n).toLocaleString("en-IN");
}
function fmtDate(d) {
  return new Date(d).toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}
function statusBadge(s) {
  const map = {
    Pending: "badge-warning",
    Processing: "badge-info",
    Shipped: "badge-info",
    Delivered: "badge-success",
    Returned: "badge-danger",
    Cancelled: "badge-danger",
    "Pending Approval": "badge-warning",
    Approved: "badge-success",
    New: "badge-warning",
    "Under Review": "badge-info",
    Rejected: "badge-danger",
    Unread: "badge-warning",
    Read: "badge-neutral",
    Replied: "badge-success",
    Archived: "badge-neutral",
    Active: "badge-success",
    Inactive: "badge-neutral",
    Expired: "badge-danger",
    Open: "badge-danger",
    "In Progress": "badge-warning",
    Resolved: "badge-success",
    Closed: "badge-neutral",
    "On Hold": "badge-warning",
    Draft: "badge-neutral",
    "Coming Soon": "badge-info",
    "Temporarily Closed": "badge-warning",
    Success: "badge-success",
    Refunded: "badge-warning",
    High: "badge-danger",
    Medium: "badge-warning",
    Low: "badge-neutral",
  };
  return `<span class="badge ${map[s] || "badge-neutral"}">${s}</span>`;
}
function showToast(msg, dur = 3000) {
  const t = document.getElementById("toast");
  if (!t) return;
  document.getElementById("toast-msg").textContent = msg;
  t.classList.add("show");
  setTimeout(() => t.classList.remove("show"), dur);
}
function openModal(id) {
  document.getElementById(id).classList.add("open");
}
function closeModal(id) {
  document.getElementById(id).classList.remove("open");
}
function triggerUpload(id) {
  document.getElementById(id).click();
}
